language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config --global user.name "FormatToday"
  - git config --global user.email "616099456@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${token}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/FormatToday/FormatToday.github.io.git